/* ── Polish labels for the component spec tree ──────────
 * Category, subcategory and spec-key names arrive from the backend in English
 * (free text written by the model), so they are translated here, at display
 * time only. Lookup is case-insensitive; anything not in the dictionary is
 * shown unchanged. Spec values and component names are data and never
 * translated. */

const LABELS: Record<string, string> = {
  // Categories — bike
  'frame': 'Rama',
  'drivetrain': 'Napęd',
  'brakes': 'Hamulce',
  'wheels': 'Koła',
  'cockpit': 'Kokpit',
  'saddle & seatpost': 'Siodło i sztyca',
  'lighting': 'Oświetlenie',
  'accessories': 'Akcesoria',
  'electric / powertrain': 'Napęd elektryczny',
  // Categories — equipment
  'helmets': 'Kaski',
  'lights & electronics': 'Oświetlenie i elektronika',
  'locks & security': 'Zapięcia i zabezpieczenia',
  'apparel, bags & accessories': 'Odzież, torby i akcesoria',

  // Subcategories — frame & suspension
  'fork': 'Widelec',
  'seatpost clamp': 'Obejma sztycy',
  'seat clamp': 'Obejma sztycy',
  'seat collar': 'Obejma sztycy',
  'rear shock': 'Amortyzator tylny',
  'swingarm': 'Wahacz',
  // Subcategories — drivetrain
  'rear derailleur': 'Przerzutka tylna',
  'front derailleur': 'Przerzutka przednia',
  'cassette': 'Kaseta',
  'crank': 'Korba',
  'bottom bracket': 'Suport',
  'chain': 'Łańcuch',
  'chainring': 'Zębatka przednia',
  'freewheel': 'Wolnobieg',
  'sprocket': 'Zębatka',
  'front sprocket': 'Zębatka przednia',
  'rear sprocket': 'Zębatka tylna',
  'rear cog': 'Zębatka tylna',
  'cog': 'Zębatka tylna',
  'chain guide': 'Prowadnica łańcucha',
  'chainguide': 'Prowadnica łańcucha',
  'chainguard': 'Osłona łańcucha',
  'chain guard': 'Osłona łańcucha',
  'shifter': 'Manetka',
  'shifters': 'Manetki',
  'shift lever': 'Manetka',
  'groupset': 'Grupa osprzętu',
  'gearing': 'Przełożenia',
  'gears': 'Biegi',
  'gear': 'Bieg',
  'gear system': 'System przełożeń',
  'gearbox': 'Przekładnia',
  'gear hub': 'Piasta z przerzutką wewnętrzną',
  'hub gear': 'Piasta z przerzutką wewnętrzną',
  'hub gears': 'Piasta z przerzutką wewnętrzną',
  'internal gear hub': 'Piasta z przerzutką wewnętrzną',
  'internal geared hub': 'Piasta z przerzutką wewnętrzną',
  'rear hub gear': 'Piasta z przerzutką wewnętrzną',
  'rear hub (internal gear)': 'Piasta z przerzutką wewnętrzną',
  'rear hub / internal gear hub': 'Piasta z przerzutką wewnętrzną',
  'belt': 'Pasek napędowy',
  'belt drive': 'Napęd pasowy',
  // Subcategories — brakes
  'brake lever': 'Klamka hamulca',
  'brake levers': 'Klamki hamulcowe',
  'brake lever front': 'Klamka hamulca przedniego',
  'brake lever rear': 'Klamka hamulca tylnego',
  'levers': 'Klamki',
  'brake rotor': 'Tarcza hamulcowa',
  'rotors': 'Tarcze hamulcowe',
  'brake front': 'Hamulec przedni',
  'brake (front)': 'Hamulec przedni',
  'front brake': 'Hamulec przedni',
  'front brakes': 'Hamulec przedni',
  'brake rear': 'Hamulec tylny',
  'brake (rear)': 'Hamulec tylny',
  'rear brake': 'Hamulec tylny',
  'brake caliper': 'Zacisk hamulca',
  'brake calipers': 'Zaciski hamulcowe',
  'front caliper': 'Zacisk przedni',
  'rear caliper': 'Zacisk tylny',
  'brake pads': 'Klocki hamulcowe',
  'coaster brake': 'Hamulec torpedo',
  'parking brake': 'Hamulec postojowy',
  'regenerative braking': 'Hamowanie rekuperacyjne',
  // Subcategories — wheels
  'front wheel': 'Koło przednie',
  'front wheels': 'Koła przednie',
  'rear wheel': 'Koło tylne',
  'rear wheels': 'Koła tylne',
  'wheelset': 'Zestaw kół',
  'tyres': 'Opony',
  'tires': 'Opony',
  'tyre': 'Opona',
  'front tyre': 'Opona przednia',
  'front tyres': 'Opony przednie',
  'rear tyre': 'Opona tylna',
  'tubes': 'Dętki',
  'thru axle front': 'Oś przelotowa przednia',
  'thru axle rear': 'Oś przelotowa tylna',
  'axles': 'Osie',
  'hub (front)': 'Piasta przednia',
  'hub (rear)': 'Piasta tylna',
  'rims': 'Obręcze',
  'rim front': 'Obręcz przednia',
  'rim rear': 'Obręcz tylna',
  'spokes front': 'Szprychy przednie',
  'spokes rear': 'Szprychy tylne',
  // Subcategories — cockpit & saddle
  'handlebar': 'Kierownica',
  'stem': 'Mostek',
  'handlebar / stem': 'Kierownica / mostek',
  'bar tape': 'Owijka',
  'grips': 'Chwyty',
  'headset': 'Stery',
  'saddle': 'Siodło',
  'dropper lever': 'Manetka sztycy regulowanej',
  // Subcategories — lighting
  'reflectors': 'Odblaski',
  'lights': 'Oświetlenie',
  'integrated lights': 'Zintegrowane oświetlenie',
  'front light': 'Lampka przednia',
  'headlight': 'Reflektor przedni',
  'rear light': 'Lampka tylna',
  'rear lights': 'Lampki tylne',
  'tail light': 'Lampka tylna',
  'taillight': 'Lampka tylna',
  'side light': 'Światło boczne',
  'side lights': 'Światła boczne',
  'brake light': 'Światło stopu',
  'indicators': 'Kierunkowskazy',
  'turn indicators': 'Kierunkowskazy',
  'turn signals': 'Kierunkowskazy',
  'mirrors': 'Lusterka',
  // Subcategories — accessories
  'tool': 'Narzędzie',
  'tool kit': 'Zestaw narzędzi',
  'pedals': 'Pedały',
  'included items': 'W zestawie',
  'optional accessories': 'Akcesoria opcjonalne',
  'kickstand': 'Nóżka',
  'stand': 'Nóżka',
  'fenders': 'Błotniki',
  'mudguards': 'Błotniki',
  'rack': 'Bagażnik',
  'rear rack': 'Bagażnik tylny',
  'rear carrier': 'Bagażnik tylny',
  'front carrier': 'Bagażnik przedni',
  'carriers': 'Bagażniki',
  'bell': 'Dzwonek',
  'lock': 'Zapięcie',
  'pump': 'Pompka',
  'basket': 'Kosz',
  'footrest': 'Podnóżek',
  'passenger equipment': 'Wyposażenie dla pasażera',
  'cargo box': 'Skrzynia ładunkowa',
  'cargo bucket': 'Skrzynia ładunkowa',
  'cargo platform': 'Platforma ładunkowa',
  'running boards': 'Podesty',
  'locker': 'Schowek',
  // Subcategories — e-bike
  'motor': 'Silnik',
  'battery': 'Bateria',
  'di2 battery': 'Bateria Di2',
  'charger': 'Ładowarka',
  'di2 charger': 'Ładowarka Di2',
  'display': 'Wyświetlacz',
  'controller': 'Sterownik',
  'display & controller': 'Wyświetlacz i sterownik',
  'display & controls': 'Wyświetlacz i sterowanie',
  'sensors': 'Czujniki',
  'pedal-assist sensor': 'Czujnik wspomagania',
  'throttle': 'Manetka gazu',
  'assist modes': 'Tryby wspomagania',
  'assist class': 'Klasa wspomagania',
  'top speed': 'Prędkość maksymalna',
  'range extender': 'Dodatkowa bateria',
  'connectivity': 'Łączność',
  'smart features': 'Funkcje smart',
  // Subcategories — equipment
  'build & portability': 'Konstrukcja i przenośność',
  'capacity & features': 'Pojemność i funkcje',
  'construction': 'Konstrukcja',
  'fit & comfort': 'Dopasowanie i komfort',
  'lock type': 'Typ zapięcia',
  'materials & construction': 'Materiały i konstrukcja',
  'mounting & build': 'Montaż i konstrukcja',
  'output & optics': 'Moc i optyka',
  'power': 'Moc',
  'safety': 'Bezpieczeństwo',
  'security': 'Zabezpieczenia',

  // Spec keys — general
  'weight': 'Waga',
  'material': 'Materiał',
  'size': 'Rozmiar',
  'sizes': 'Rozmiary',
  'available sizes': 'Dostępne rozmiary',
  'sizes available': 'Dostępne rozmiary',
  'type': 'Typ',
  'standard': 'Standard',
  'range': 'Zakres',
  'diameter': 'Średnica',
  'width': 'Szerokość',
  'length': 'Długość',
  'height': 'Wysokość',
  'thickness': 'Grubość',
  'dimension': 'Wymiar',
  'dimensions': 'Wymiary',
  'overall dimensions': 'Wymiary całkowite',
  'gender': 'Płeć',
  'color': 'Kolor',
  'colour': 'Kolor',
  'colors': 'Kolory',
  'colours': 'Kolory',
  'color options': 'Dostępne kolory',
  'finish': 'Wykończenie',
  'brand': 'Marka',
  'model': 'Model',
  'model year': 'Rok modelowy',
  'year': 'Rok',
  'series': 'Seria',
  'manufacturer': 'Producent',
  'origin': 'Pochodzenie',
  'made in': 'Kraj produkcji',
  'country of origin': 'Kraj produkcji',
  'style': 'Styl',
  'design': 'Konstrukcja',
  'feature': 'Funkcja',
  'features': 'Funkcje',
  'options': 'Opcje',
  'configuration': 'Konfiguracja',
  'compatibility': 'Kompatybilność',
  'compatible': 'Kompatybilność',
  'certification': 'Certyfikat',
  'safety certification': 'Certyfikat bezpieczeństwa',
  'includes': 'W zestawie',
  'supplied with': 'W zestawie',
  'integrated': 'Zintegrowane',
  'integration': 'Integracja',
  'position': 'Pozycja',
  'location': 'Umiejscowienie',
  'placement': 'Umiejscowienie',
  'mount': 'Mocowanie',
  'mounts': 'Mocowania',
  'mounting': 'Montaż',
  'mount type': 'Typ mocowania',
  'clamp': 'Obejma',
  'clamp diameter': 'Średnica obejmy',
  'clamp size': 'Rozmiar obejmy',
  'adjustment': 'Regulacja',
  'adjustable': 'Regulacja',
  'angle': 'Kąt',
  'offset': 'Offset',
  'rise': 'Wznios',
  'reach': 'Reach',
  'stack': 'Stack',
  'drop': 'Drop',
  'thread': 'Gwint',
  'bearings': 'Łożyska',
  'bearing': 'Łożysko',
  'bearing type': 'Typ łożysk',
  'capacity': 'Pojemność',
  'volume': 'Pojemność',
  'warranty': 'Gwarancja',
  'price': 'Cena',
  'note': 'Uwaga',
  'condition': 'Stan',
  'intended use': 'Przeznaczenie',
  'purpose': 'Przeznaczenie',
  'terrain': 'Teren',
  'rating': 'Klasa',
  'water resistance': 'Wodoodporność',
  'weather protection': 'Ochrona przed pogodą',
  'protection': 'Ochrona',
  'padding': 'Wyściółka',
  'removable': 'Wyjmowana',
  'maintenance': 'Konserwacja',
  'tools': 'Narzędzia',
  'cable routing': 'Prowadzenie linek',
  'routing': 'Prowadzenie linek',
  'complete weight': 'Waga całkowita',
  'total weight': 'Waga całkowita',
  'bike weight': 'Waga roweru',
  'complete bike weight': 'Waga roweru',
  'total bike weight': 'Waga roweru',
  'approximate weight': 'Waga przybliżona',
  'frame weight': 'Waga ramy',
  'weight limit': 'Limit wagi',
  'max weight': 'Maks. waga',
  'max load': 'Maks. obciążenie',
  'maximum load': 'Maks. obciążenie',
  'load capacity': 'Ładowność',
  'payload': 'Ładowność',
  'payload capacity': 'Ładowność',
  'total weight limit': 'Maks. obciążenie całkowite',
  'max rider weight': 'Maks. waga rowerzysty',
  'maximum rider weight': 'Maks. waga rowerzysty',
  'rider weight limit': 'Maks. waga rowerzysty',
  'rider height': 'Wzrost rowerzysty',
  'rider height range': 'Zakres wzrostu rowerzysty',
  'recommended rider height': 'Zalecany wzrost rowerzysty',
  'age range': 'Przedział wiekowy',
  'recommended age': 'Zalecany wiek',
  'rider age': 'Wiek rowerzysty',
  'inseam': 'Przekrok',
  'inside leg': 'Przekrok',

  // Spec keys — frame & geometry
  'axle dimension': 'Wymiar osi',
  'rear axle dimension': 'Wymiar osi tylnej',
  'tyre clearance': 'Prześwit na oponę',
  'tire clearance': 'Prześwit na oponę',
  'max tyre clearance': 'Maks. prześwit na oponę',
  'max tire clearance': 'Maks. prześwit na oponę',
  'max tire size': 'Maks. rozmiar opony',
  'max clearance': 'Maks. prześwit',
  'steer tube diameter': 'Średnica rury sterowej',
  'steer tube': 'Rura sterowa',
  'steerer': 'Rura sterowa',
  'steerer tube': 'Rura sterowa',
  'steerer length': 'Długość rury sterowej',
  'steerer tube length': 'Długość rury sterowej',
  'steerer material': 'Materiał rury sterowej',
  'tapered steerer': 'Stożkowa rura sterowa',
  'frame size': 'Rozmiar ramy',
  'frame sizes': 'Rozmiary ramy',
  'frame style': 'Styl ramy',
  'frame type': 'Typ ramy',
  'frame design': 'Konstrukcja ramy',
  'geometry': 'Geometria',
  'head tube': 'Główka ramy',
  'head tube angle': 'Kąt główki ramy',
  'head angle': 'Kąt główki ramy',
  'head tube length': 'Długość główki ramy',
  'seat tube angle': 'Kąt rury podsiodłowej',
  'seat angle': 'Kąt rury podsiodłowej',
  'seat tube length': 'Długość rury podsiodłowej',
  'top tube length': 'Długość rury górnej',
  'effective top tube': 'Efektywna długość rury górnej',
  'effective top tube length': 'Efektywna długość rury górnej',
  'chainstay length': 'Długość tylnych widełek',
  'wheelbase': 'Rozstaw osi',
  'standover height': 'Wysokość przekroku',
  'standover': 'Wysokość przekroku',
  'bb drop': 'Obniżenie suportu',
  'bottom bracket drop': 'Obniżenie suportu',
  'bb height': 'Wysokość suportu',
  'bottom bracket height': 'Wysokość suportu',
  'bottom bracket shell': 'Mufa suportu',
  'bb shell': 'Mufa suportu',
  'bottom bracket standard': 'Standard suportu',
  'bb type': 'Typ suportu',
  'derailleur hanger': 'Hak przerzutki',
  'dropout': 'Hak',
  'dropouts': 'Haki',
  'rear dropouts': 'Haki tylne',
  'axle to crown': 'Axle-to-crown',
  'axle-to-crown': 'Axle-to-crown',
  'fork length': 'Długość widelca',
  'fork offset': 'Offset widelca',
  'fork rake': 'Offset widelca',
  'travel': 'Skok',
  'rear travel': 'Skok tylny',
  'front travel': 'Skok przedni',
  'suspension': 'Amortyzacja',
  'suspension travel': 'Skok amortyzacji',
  'stanchion diameter': 'Średnica goleni',
  'lockout': 'Blokada',
  'damper': 'Tłumik',
  'spring': 'Sprężyna',
  'spring type': 'Typ sprężyny',
  'preload': 'Napięcie wstępne',
  'shock size': 'Rozmiar amortyzatora',
  'brake mount': 'Mocowanie hamulca',
  'brake mounts': 'Mocowania hamulca',
  'bottle mounts': 'Mocowania na bidon',
  'accessory mounts': 'Mocowania akcesoriów',
  'fender compatible': 'Mocowania na błotniki',
  'eyelets': 'Otwory montażowe',
  'tubing': 'Rury',
  'welding': 'Spawanie',
  'folded dimensions': 'Wymiary po złożeniu',
  'folding time': 'Czas składania',

  // Spec keys — drivetrain
  'sprockets': 'Zębatki',
  'chainrings': 'Zębatki przednie',
  'chainring teeth': 'Liczba zębów zębatki',
  'chainring size': 'Rozmiar zębatki',
  'teeth': 'Liczba zębów',
  'tooth count': 'Liczba zębów',
  'speeds': 'Liczba biegów',
  'speed': 'Liczba biegów',
  'number of gears': 'Liczba biegów',
  'gear range': 'Zakres przełożeń',
  'gear ratios': 'Przełożenia',
  'crank length': 'Długość korby',
  'crank arm length': 'Długość korby',
  'arm length': 'Długość ramienia',
  'spindle': 'Oś korby',
  'spindle length': 'Długość osi',
  'q factor': 'Q-factor',
  'chainline': 'Linia łańcucha',
  'chain line': 'Linia łańcucha',
  'links': 'Ogniwa',
  'pitch': 'Podziałka',
  'clutch': 'Sprzęgło',
  'cage': 'Wózek',
  'cage type': 'Typ wózka',
  'max cog': 'Maks. zębatka',
  'shifting': 'Zmiana biegów',
  'shift type': 'Typ zmiany biegów',
  'actuation': 'Sposób uruchamiania',
  'freehub': 'Bębenek',
  'free hub': 'Bębenek',

  // Spec keys — brakes & wheels
  'pistons': 'Tłoczki',
  'rotor mount': 'Mocowanie tarczy',
  'rotor size': 'Rozmiar tarczy',
  'rotor size front': 'Rozmiar tarczy przedniej',
  'rotor size rear': 'Rozmiar tarczy tylnej',
  'max rotor size': 'Maks. rozmiar tarczy',
  'brake type': 'Typ hamulców',
  'pad type': 'Typ klocków',
  'pads': 'Klocki',
  'fluid': 'Płyn hamulcowy',
  'lever material': 'Materiał klamki',
  'inner width': 'Szerokość wewnętrzna',
  'internal width': 'Szerokość wewnętrzna',
  'rim inner width': 'Szerokość wewnętrzna obręczy',
  'rim height': 'Wysokość obręczy',
  'rim material': 'Materiał obręczy',
  'rim type': 'Typ obręczy',
  'rim size': 'Rozmiar obręczy',
  'rim width': 'Szerokość obręczy',
  'rim': 'Obręcz',
  'hub': 'Piasta',
  'hub type': 'Typ piasty',
  'hub spacing': 'Rozstaw piasty',
  'hub material': 'Materiał piasty',
  'spacing': 'Rozstaw',
  'rear spacing': 'Rozstaw tylny',
  'axle spacing': 'Rozstaw osi piasty',
  'axle': 'Oś',
  'axle type': 'Typ osi',
  'axle standard': 'Standard osi',
  'rear axle': 'Oś tylna',
  'front axle': 'Oś przednia',
  'thru-axle': 'Oś przelotowa',
  'quick release': 'Szybkozamykacz',
  'spokes': 'Szprychy',
  'spoke count': 'Liczba szprych',
  'spoke holes': 'Otwory na szprychy',
  'spoke gauge': 'Grubość szprych',
  'holes': 'Liczba otworów',
  'nipples': 'Nyple',
  'engagement': 'Zazębienie',
  'wheel size': 'Rozmiar kół',
  'tire width': 'Szerokość opony',
  'tyre size': 'Rozmiar opony',
  'tubeless': 'Tubeless',
  'tubeless ready': 'Gotowe do tubeless',
  'casing': 'Karkas',
  'compound': 'Mieszanka gumy',
  'tread': 'Bieżnik',
  'bead': 'Stopka',
  'sidewall': 'Ścianka boczna',
  'puncture protection': 'Ochrona przed przebiciem',
  'pressure range': 'Zakres ciśnienia',
  'recommended pressure': 'Zalecane ciśnienie',
  'valve': 'Wentyl',
  'valve type': 'Typ wentyla',
  'gauge': 'Grubość',

  // Spec keys — cockpit & saddle
  'handlebar width': 'Szerokość kierownicy',
  'bar width': 'Szerokość kierownicy',
  'handlebar diameter': 'Średnica kierownicy',
  'bar diameter': 'Średnica kierownicy',
  'handlebar clamp': 'Średnica mocowania kierownicy',
  'bar clamp': 'Średnica mocowania kierownicy',
  'handlebar rise': 'Wznios kierownicy',
  'handlebar type': 'Typ kierownicy',
  'handlebar material': 'Materiał kierownicy',
  'backsweep': 'Wygięcie do tyłu',
  'back sweep': 'Wygięcie do tyłu',
  'upsweep': 'Wygięcie w górę',
  'up sweep': 'Wygięcie w górę',
  'sweep': 'Wygięcie',
  'flare': 'Rozchylenie',
  'stem length': 'Długość mostka',
  'stem angle': 'Kąt mostka',
  'stem clamp': 'Średnica mocowania mostka',
  'steerer clamp': 'Mocowanie na rurze sterowej',
  'headset standard': 'Standard sterów',
  'headset type': 'Typ sterów',
  'grip material': 'Materiał chwytów',
  'rails': 'Szyny',
  'seatpost diameter': 'Średnica sztycy',
  'seat post diameter': 'Średnica sztycy',
  'seatpost': 'Sztyca',
  'insertion depth': 'Głębokość wsunięcia',
  'max insertion': 'Maks. głębokość wsunięcia',
  'drop range': 'Zakres regulacji',
  'saddle height range': 'Zakres wysokości siodła',
  'seat height': 'Wysokość siodła',

  // Spec keys — e-bike
  'voltage': 'Napięcie',
  'input voltage': 'Napięcie wejściowe',
  'amp hours': 'Pojemność (Ah)',
  'torque': 'Moment obrotowy',
  'motor torque': 'Moment obrotowy silnika',
  'motor power': 'Moc silnika',
  'motor type': 'Typ silnika',
  'nominal power': 'Moc znamionowa',
  'rated power': 'Moc znamionowa',
  'peak power': 'Moc szczytowa',
  'power output': 'Moc wyjściowa',
  'output': 'Moc wyjściowa',
  'claimed range': 'Deklarowany zasięg',
  'charge time': 'Czas ładowania',
  'charging time': 'Czas ładowania',
  'charging': 'Ładowanie',
  'assisted speed': 'Prędkość ze wspomaganiem',
  'assist speed': 'Prędkość ze wspomaganiem',
  'assist levels': 'Poziomy wspomagania',
  'pedal assist': 'Wspomaganie pedałowania',
  'class': 'Klasa',
  'sensor': 'Czujnik',
  'sensor type': 'Typ czujnika',
  'battery type': 'Typ baterii',
  'cells': 'Ogniwa',
  'chemistry': 'Typ ogniw',
  'cycle life': 'Liczba cykli ładowania',
  'ingress rating': 'Stopień ochrony (IP)',
  'display type': 'Typ wyświetlacza',
  'controls': 'Sterowanie',

  // Spec keys — lighting & equipment
  'brightness': 'Jasność',
  'max brightness': 'Maks. jasność',
  'run time': 'Czas pracy',
  'modes': 'Tryby',
  'closure': 'Zapięcie',
  'internal dimensions': 'Wymiary wewnętrzne',
  'keys': 'Klucze',
  'mechanism': 'Mechanizm',
  'reflective': 'Elementy odblaskowe',
  'retention': 'System dopasowania',
  'rotational system': 'System ochrony rotacyjnej',
  'security rating': 'Poziom zabezpieczenia',
  'shackle': 'Kabłąk',
  'shell': 'Skorupa',
  'vents': 'Wentylacja',
  'dynamo': 'Dynamo',
  'guard': 'Osłona',

  // Remaining frequent keys
  'front': 'Przód',
  'rear': 'Tył',
  'size front': 'Rozmiar (przód)',
  'size rear': 'Rozmiar (tył)',
  'folding': 'Składanie',
  'profile': 'Profil',
  'hardware': 'Elementy montażowe',
  'interface': 'Interfejs',
  'system': 'System',
  'weight capacity': 'Ładowność',
  'fork spacing': 'Rozstaw widelca',
  'head tube diameter': 'Średnica główki ramy',
  'seat post clamp diameter': 'Średnica obejmy sztycy',
  'seatpost clamp diameter': 'Średnica obejmy sztycy',
  'stem material': 'Materiał mostka',
  'lower': 'Dolne',
  'upper': 'Górne',
  'tune': 'Strojenie',
}

// Words that often appear in a key's trailing "(…)" qualifier, e.g. "Weight (Size M)".
const QUALIFIER_WORDS: Record<string, string> = {
  front: 'przód',
  rear: 'tył',
  size: 'rozmiar',
  total: 'całkowita',
  'no battery': 'bez baterii',
  'with battery': 'z baterią',
  'without battery': 'bez baterii',
  large: 'L',
  medium: 'M',
  small: 'S',
}

function lookup(text: string): string | undefined {
  return LABELS[text.trim().toLowerCase()]
}

function translateQualifier(q: string): string {
  const whole = QUALIFIER_WORDS[q.trim().toLowerCase()]
  if (whole) return whole
  return q.replace(/\b(front|rear|size|total)\b/gi, w => QUALIFIER_WORDS[w.toLowerCase()])
}

/** Polish label for a category, subcategory or spec key; unknown text is returned unchanged. */
export function translateLabel(text: string): string {
  if (!text) return text
  const exact = lookup(text)
  if (exact) return exact

  // "Weight (Size M)" → "Waga (rozmiar M)"
  const paren = text.match(/^(.*?)\s*\(([^)]*)\)\s*$/)
  if (paren) {
    const base = lookup(paren[1])
    if (base) return `${base} (${translateQualifier(paren[2])})`
  }

  // "Front Hub" / "Rear Axle Dimension" → "Piasta (przód)" / "Wymiar osi (tył)"
  const side = text.match(/^(front|rear)\s+(.+)$/i)
  if (side) {
    const base = lookup(side[2])
    if (base) return `${base} (${QUALIFIER_WORDS[side[1].toLowerCase()]})`
  }

  // "Max Chainring" / "Maximum Width" → "Maks. zębatka przednia" / "Maks. szerokość"
  const max = text.match(/^(max|maximum)\s+(.+)$/i)
  if (max) {
    const base = lookup(max[2])
    if (base) return `Maks. ${base.charAt(0).toLowerCase()}${base.slice(1)}`
  }

  return text
}
